/*
Author: Viktor (victor318x@gmail.com)
sidebarsInterview.js (c) 2021
Desc: description
Created:  3/31/2021, 1:36:44 PM
Modified: 4/5/2021, 10:15:35 AM
*/

module.exports = {
  interview: [
    {
      type: "category",
      label: "面试",
      items: [
        {
          "JavaScript 300问": [
            "js/iq-1",
            "js/iq-2",
            "js/iq-3",
            "js/iq-4",
            "js/iq-5",
            "js/iq-6",
            "js/iq-7",
            "js/iq-8",
            "js/iq-9",
            "js/iq-10",
            "js/iq-11",
            "js/iq-12",
            "js/iq-13",
            "js/iq-14",
            "js/iq-15",
            "js/iq-16",
            "js/iq-17",
            "js/iq-18",
            "js/iq-19",
            "js/iq-20",
            "js/iq-21",
            "js/iq-22",
            "js/iq-23",
            "js/iq-24",
            "js/iq-25",
            "js/iq-26",
            "js/iq-27",
            "js/iq-28",
            "js/iq-29",
            "js/iq-30",
            "js/iq-31",
            "js/iq-32",
            "js/iq-33",
            "js/iq-34",
            // "js/iq-35",
            // "js/iq-36",
            // "js/iq-37",
            // "js/iq-38",
            // "js/iq-39",
            // "js/iq-40",
          ],
        },
        {
          "React 300问": [
            "react/iq-1", 
            "react/iq-2",
            "react/iq-3",
            "react/iq-4",
            "react/iq-5",
            "react/iq-6",
            "react/iq-7",
            "react/iq-8",
            "react/iq-9",
            "react/iq-10",
            "react/iq-11",
            "react/iq-12",
            "react/iq-13",
            "react/iq-14",
            "react/iq-15",
            "react/iq-16",
            "react/iq-17",
            "react/iq-18",
            "react/iq-19",
            "react/iq-20",
            "react/iq-21",
            "react/iq-22",
            "react/iq-23",
            "react/iq-24",
            "react/iq-25",
            "react/iq-26",
            "react/iq-27",
            "react/iq-28",
            "react/iq-29",
            "react/iq-30",
            "react/iq-31",
            "react/iq-32",
            "react/iq-33",
            "react/iq-34",
            "react/iq-35",
            "react/iq-36",
            "react/iq-37",
            "react/iq-38",
            "react/iq-39",
            "react/iq-40",
            "react/iq-41",
            "react/iq-42",
            "react/iq-43",
            "react/iq-44",
            "react/iq-45",
            "react/iq-46",
            "react/iq-47",
            "react/iq-48",
            "react/iq-49",
            "react/iq-50",
            "react/iq-51",
            "react/iq-52",
            "react/iq-53",
            "react/iq-54",
            "react/iq-55",
            "react/iq-56",
            "react/iq-57",
            "react/iq-58",
            "react/iq-59",
            "react/iq-60",
            "react/iq-61",
            "react/iq-62",
            "react/iq-63",
            "react/iq-64",
            "react/iq-65",
            "react/iq-66",
            "react/iq-67",
            "react/iq-68",
            "react/iq-69",
            "react/iq-70",
            "react/iq-71",
            "react/iq-72",
            "react/iq-73",
            "react/iq-74",
            "react/iq-75",
            "react/iq-76",
            "react/iq-77",
            "react/iq-78",
            "react/iq-79",
            "react/iq-80",
          ],
        },
      ],
    },
  ],
};
